import type { SiteContent } from "@/types/content";

/**
 * PLACEHOLDER CONTENT.
 *
 * SANJEH is a fictional supplier built as a template. Everything below is a
 * stand-in so the layout can be reviewed with realistic Persian text.
 *
 * Phone, WhatsApp and email are deliberately non-functional, on the same
 * unassigned-number convention the rest of this family uses: `.example` is the
 * IANA-reserved placeholder name, `021 0000 0000` is not a dialable number, and
 * `wa.me` answers an unassigned number with "this link is invalid" rather than
 * opening a chat with a stranger. They are structurally valid — the pattern is
 * demonstrated — and simply do not lead anywhere.
 *
 * **Nothing here asserts a fact about a real business**, and in this trade that
 * rule has teeth: there is no certification, no standards conformity, no
 * approval, no founding year, no client, no export market, no capacity figure
 * and no headcount anywhere in this repository. Physical attributes of a
 * fictional part are fine; a claim about a company is not.
 *
 * There is also no social block, unlike the editorial family. An industrial
 * buyer's enquiry route is a phone call, an email or a WhatsApp message
 * carrying a part code — not an Instagram profile — so the field was removed
 * from the model rather than filled with placeholder handles nobody would use.
 */
export const site: SiteContent = {
  brand: {
    name: "سنجه",
    latin: "SANJEH",
    line: "قطعات کنترل سیال و ابزار دقیق برای خطوط صنعتی.",
  },

  seo: {
    title: "سنجه — قطعات کنترل سیال و ابزار دقیق",
    titleTemplate: "%s — سنجه",
    description:
      "سنجه سازندهٔ شیرآلات کنترلی، ابزار دقیق و اتصالات خط است؛ نه قطعه با بازهٔ سایز، فشار و دمای کاری مشخص، به همراه مشخصات کامل و مقایسهٔ فنی.",
    /** Generated by `scripts/generate-og.mjs` — a raster, not an SVG, because
     *  no social crawler renders an SVG share card. A JPEG rather than a PNG
     *  since half the card is now a photograph, which a PNG stores badly. */
    ogImage: {
      src: "/media/og-card.jpg",
      alt: "نیمهٔ چپ عکس شیر کنترلی گلوب با بدنهٔ فولاد زنگ‌نزن و دو فلنج، نیمهٔ راست زمینهٔ سفید با نشان عقربه‌ای سنجه، نام لاتین برند و خط‌کشی مدرج",
      width: 1200,
      height: 630,
    },
  },

  /**
   * Route paths are identical to every other repository in this family, on
   * purpose: keeping them structurally the same is worth more than a prettier
   * URL. Only the Persian words change.
   *
   * Hrefs are written from the site root so the header works on every page — a
   * bare `#contact` resolves against whatever page the header happens to be
   * rendered on, which is nothing at all outside the homepage.
   */
  nav: [
    { label: "فهرست محصولات", href: "/products/" },
    { label: "آرشیو فنی", href: "/gallery/" },
    { label: "دربارهٔ ما", href: "/about/" },
    { label: "تماس", href: "/#contact" },
  ],

  headerCta: { label: "درخواست استعلام", href: "/#contact" },

  contact: {
    /** Deliberately without a street or a number: a fabricated postal address
     *  is a verifiable-looking fact about a company that does not exist. The
     *  trailing zeros match the phone convention and read as a stand-in. */
    address: "تهران، شهرک صنعتی — واحد ۰۰",
    city: "تهران",
    phone: "۰۲۱ — ۰۰۰۰ ۰۰۰۰",
    phoneHref: "+982100000000",
    /** Latin digits, no punctuation — `wa.me` accepts nothing else, and Persian
     *  digits are not matched by `\d`. */
    whatsapp: "989000000000",
    email: "info@sanjeh.example",
    hours: "شنبه تا چهارشنبه، ۸ تا ۱۷",
  },

  /**
   * Empty on purpose, and the footer hides the row while it is. A privacy
   * policy and terms of use are the one category of content where inventing
   * plausible text is actively harmful. Add real entries here when real
   * policies exist and the row comes back with no change to any component.
   */
  legal: [],

  footer: {
    navHeading: "فهرست",
    contactHeading: "تماس",
  },

  copyright: "© ۱۴۰۵ سنجه — تمام حقوق محفوظ است.",
};
